version: '2'

services:
  app:
    image: 'app:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8082:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/newdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=vivi
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vivi
      - POSTGRES_DB=newdb
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
  ui:
    image: '=ui:latest'
      build:
        context: ../../../totoappui
        dockerfile: ../../../totoappui/Dockerfile
      container_name: ui
    volumes:
      - /app/node_modules
      - ./ui:/app
      ports:
        - "3000:8080"
